name: Build
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    if: "!contains(github.event.commits[0].message, '[ci-skip]')"
    steps:
      - uses: actions/checkout@v2
      - name: Notify Discord
        uses: BillyGalbreath/actions-status-discord@main
        if: success()
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK }}
          noprefix: true
          title: New build of Pl3xMap is ready!
          description: |
            testing 1 2 3
            **multi-lines**
            go
            brrr
